### ISSUE TITLE
【依頼】ChatSpace挙動確認

### ISSUE THREAD

**Issue by k1y0r4k4** [k1y0r4k4/chat-space#10]
# IPアドレス
175.41.197.230

**Comment by naru6117** [comment]
ご提出ありがとうございます！
挙動確認させて頂いたところ、以下の不備が見受けられましたので修正をお願いします！

[修正箇所]
**①「Edit」ボタンのデザインを見本と同じにしましょう（下線をなくす・色を同じにする）**

**②送信したメッセージの送信日時がきちんと表示されるようにしましょう（非同期通信、自動更新ともに）**
　（リロードすると正しく表示されますが、していない場合「undefined」と表示されます）

修正が完了次第、以下のChatSpace完了報告フォームに再度こちらのissueのURLを記載していただき提出お願いします！
※新しいissueを作っていただく必要はありません
https://docs.google.com/forms/d/e/1FAIpQLSfNKbknajjCthhkGSyIkhspu2hOAxnESHweNLX2LQJdlO5vGw/viewform

**Comment by k1y0r4k4** [comment]
ご返答いただきありがとうございます。

ご指摘いただいた２点について対応いたしました。
再度ご確認いただいてもよろしいでしょうか。よろしくお願いいたします。

**Comment by mutorisa** [comment]
修正後、再度ご提出ありがとうございました‼︎

上記２点について、バッチリ修正されていました。ありがとうございます！

再度挙動確認させていただいたところ、以下３点の不備が見受けられましたので修正をお願いします。

[修正箇所]
〜参考カリキュラム〜
https://master.tech-camp.in/curriculums/3944

**①サイドバーのグループ編集&アカウント編集のアイコンの位置**
　
<img width="300" alt="アイコン修正" src="https://user-images.githubusercontent.com/65144927/81780420-778eba00-9531-11ea-9d72-1fb2711ae1aa.png">

<img width="300" alt="スクリーンショット 2020-05-13 15 33 26" src="https://user-images.githubusercontent.com/65144927/81780453-82e1e580-9531-11ea-88fd-6a55eda49cd8.png">

**②グループ名&メンバーの文字サイズ**
<img width="1142" alt="文字サイズ修正" src="https://user-images.githubusercontent.com/65144927/81780531-a2790e00-9531-11ea-8c65-5075220085ab.png">

<img width="1142" alt="文字サイズ" src="https://user-images.githubusercontent.com/65144927/81780557-ab69df80-9531-11ea-96af-492d7e34ba91.png">


**③メッセージ入力フォームを見本と同じように調整しましょう。**
<img width="691" alt="投稿フォーム見本" src="https://user-images.githubusercontent.com/65144927/81780624-cccacb80-9531-11ea-98ae-7100d57b388f.png">

修正が完了次第、以下のChatSpace完了報告フォームに再度こちらのissueのURLを記載していただきご提出をお願いします！
※新しいissueを作っていただく必要はありません
https://docs.google.com/forms/ d / e / 1FAIpQLSfNKbknajjCthhkGSyIkhspu2hOAxnESHweNLX2LQJdlO5vGw / viewform

**Comment by k1y0r4k4** [comment]
上記、いただきました内容を元に修正いたしました。

お手数ですが、再度のご確認をお願いいたします。

**Comment by naru6117** [comment]
ご提出ありがとうございます！
確認させて頂きましたが、全く問題ございませんでしたのでLGTMとさせて頂きます🎉
おめでとうございます！

**Comment by k1y0r4k4** [comment]
ありがとうございました！
